/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeInsights: typeof import('./src/components/CodeInsights.vue')['default']
    DashboardHome: typeof import('./src/components/DashboardHome.vue')['default']
    DeploymentInsights: typeof import('./src/components/DeploymentInsights.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderInsights: typeof import('./src/components/HeaderInsights.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Insights: typeof import('./src/components/Insights.vue')['default']
    IssueManagmentInsights: typeof import('./src/components/IssueManagmentInsights.vue')['default']
    ManagementView: typeof import('./src/components/ManagementView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
